import React, { useState } from "react";
import { X, Printer, Copy, Check, Scale } from "lucide-react";
import type { PDFHighlight } from "@/types/file";
import { toast } from "sonner";

interface ResearchBriefModalProps {
  isOpen: boolean;
  onClose: () => void;
  caseTitle: string;
  courtName: string;
  orderDate: string;
  cnr: string;
  notes: string;
  highlights: PDFHighlight[];
  tags: string[];
}

export function ResearchBriefModal({
  isOpen,
  onClose,
  caseTitle,
  courtName,
  orderDate,
  cnr,
  notes,
  highlights,
  tags,
}: ResearchBriefModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdownBrief = () => {
    let md = `# CASE RESEARCH BRIEF: ${caseTitle}\n\n`;
    md += `**Court**: ${courtName}\n`;
    md += `**CNR**: ${cnr}\n`;
    md += `**Order Date**: ${orderDate}\n`;
    md += `**Generated**: ${new Date().toLocaleDateString()}\n\n`;

    if (tags.length > 0) {
      md += `**Tags**: ${tags.map((t) => `#${t}`).join(" ")}\n\n`;
    }

    md += `---\n\n## 📝 Executive Notes & Hearing Strategy\n\n`;
    md += notes ? notes : `*No written notes recorded.*\n\n`;

    md += `\n---\n\n## 📌 Key Highlighted Citations & Pointers (${highlights.length})\n\n`;
    if (highlights.length === 0) {
      md += `*No text excerpts highlighted.*\n\n`;
    } else {
      highlights.forEach((h, idx) => {
        md += `### Citation ${idx + 1} (Page ${h.pageNum})\n`;
        md += `> "${h.text}"\n\n`;
      });
    }

    md += `---\n*Generated by SUITS AI-Powered Court Intelligence Vault*`;
    return md;
  };

  const handleCopy = () => {
    const text = generateMarkdownBrief();
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Research Brief copied to clipboard as Markdown.");
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-[1000] flex items-center justify-center p-3 sm:p-6 animate-fade-in select-none">
      {/* Backdrop */}
      <div className="fixed inset-0 bg-black/80 backdrop-blur-md" onClick={onClose} />

      {/* Printable Brief Modal Window */}
      <div
        className="relative z-10 w-full max-w-3xl max-h-[90vh] flex flex-col rounded-2xl overflow-hidden border shadow-2xl animate-spring-in"
        style={{
          background: "var(--card)",
          borderColor: "var(--border)",
        }}
      >
        {/* Modal Top Bar */}
        <div
          className="flex items-center justify-between px-5 py-3 border-b select-none flex-shrink-0"
          style={{ background: "var(--surface)", borderColor: "var(--border)" }}
        >
          <div className="flex items-center gap-2">
            <Scale size={16} style={{ color: "var(--brass)" }} />
            <h3 className="text-xs font-bold font-display" style={{ color: "var(--ink)" }}>
              Case Research Brief Preview
            </h3>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="btn btn-ghost flex items-center gap-1.5 text-xs px-3 py-1 rounded-lg border cursor-pointer"
              style={{ borderColor: "var(--border)", color: "var(--ink)" }}
            >
              {copied ? <Check size={13} className="text-emerald-500" /> : <Copy size={13} />}
              <span>{copied ? "Copied" : "Copy MD"}</span>
            </button>

            <button
              onClick={handlePrint}
              className="px-3 py-1 rounded-lg text-xs font-semibold flex items-center gap-1.5 cursor-pointer shadow-sm"
              style={{
                background: "var(--brass)",
                color: "var(--on-primary)",
              }}
            >
              <Printer size={13} />
              <span>Print / Save PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-1 rounded-md opacity-60 hover:opacity-100 cursor-pointer ml-1"
              style={{ color: "var(--ink)" }}
            >
              <X size={16} />
            </button>
          </div>
        </div>

        {/* Printable Document Sheet Body */}
        <div
          className="flex-1 overflow-y-auto p-6 sm:p-10 select-text"
          style={{ background: "var(--surface-dim)" }}
        >
          {/* Isolated Paper Sheet with Explicit High-Contrast Colors (Guaranteed 100% Readability in Dark & Light Modes) */}
          <div
            id="brief-paper-sheet"
            className="p-8 sm:p-12 rounded-xl border shadow-xl space-y-6 mx-auto max-w-2xl"
            style={{
              backgroundColor: "#FFFFFF",
              color: "#0F172A",
              borderColor: "#E2E8F0",
              fontFamily: "'Source Serif 4', Georgia, serif",
            }}
          >
            {/* Brief Header */}
            <div className="border-b pb-5 space-y-2" style={{ borderColor: "#E2E8F0" }}>
              <div
                className="flex items-center justify-between text-xs font-mono font-medium"
                style={{ color: "#64748B" }}
              >
                <span>LEGAL RESEARCH BRIEF</span>
                <span>{new Date().toLocaleDateString()}</span>
              </div>

              <h1
                className="text-xl sm:text-2xl font-bold leading-snug"
                style={{
                  color: "#0F172A",
                  fontFamily: "'Source Serif 4', Georgia, serif",
                }}
              >
                {caseTitle}
              </h1>

              <div
                className="flex flex-wrap items-center gap-x-4 gap-y-1 text-xs font-mono"
                style={{ color: "#475569" }}
              >
                <span>
                  <strong style={{ color: "#0F172A" }}>Court:</strong> {courtName}
                </span>
                <span>
                  <strong style={{ color: "#0F172A" }}>CNR:</strong> {cnr}
                </span>
                <span>
                  <strong style={{ color: "#0F172A" }}>Order Date:</strong> {orderDate}
                </span>
              </div>

              {tags.length > 0 && (
                <div className="flex flex-wrap gap-1.5 pt-2">
                  {tags.map((t) => (
                    <span
                      key={t}
                      className="px-2 py-0.5 rounded font-mono text-[11px] font-semibold border"
                      style={{
                        backgroundColor: "#FEF3C7",
                        color: "#92400E",
                        borderColor: "#FDE68A",
                      }}
                    >
                      #{t}
                    </span>
                  ))}
                </div>
              )}
            </div>

            {/* Section 1: Executive Notes & Strategy */}
            <div className="space-y-3">
              <h2
                className="text-xs font-bold uppercase tracking-wider font-mono border-b pb-1.5"
                style={{
                  color: "#92400E",
                  borderColor: "#FDE68A",
                }}
              >
                1. Executive Notes & Trial Arguments
              </h2>
              {notes ? (
                <div
                  className="text-xs leading-relaxed whitespace-pre-wrap font-sans"
                  style={{
                    color: "#1E293B",
                    fontFamily: "'IBM Plex Sans', system-ui, sans-serif",
                    lineHeight: 1.8,
                  }}
                >
                  {notes}
                </div>
              ) : (
                <p className="text-xs italic" style={{ color: "#94A3B8" }}>
                  No written notes recorded for this order.
                </p>
              )}
            </div>

            {/* Section 2: Key Highlighted Excerpts */}
            <div className="space-y-3 pt-2">
              <h2
                className="text-xs font-bold uppercase tracking-wider font-mono border-b pb-1.5"
                style={{
                  color: "#92400E",
                  borderColor: "#FDE68A",
                }}
              >
                2. Key Highlighted Excerpts & Statutory Grounds ({highlights.length})
              </h2>
              {highlights.length === 0 ? (
                <p className="text-xs italic" style={{ color: "#94A3B8" }}>
                  No highlighted extracts in this record.
                </p>
              ) : (
                <div className="space-y-4 pt-1">
                  {highlights.map((h, idx) => (
                    <div
                      key={h.id || idx}
                      className="p-3.5 rounded-lg border space-y-1.5"
                      style={{
                        backgroundColor: "#F8FAFC",
                        borderColor: "#E2E8F0",
                      }}
                    >
                      <div
                        className="flex items-center justify-between text-[11px] font-mono font-bold"
                        style={{ color: "#475569" }}
                      >
                        <span>EXCERPT #{idx + 1}</span>
                        <span
                          className="px-1.5 py-0.5 rounded text-[10.5px] font-bold"
                          style={{
                            backgroundColor: "#FEF3C7",
                            color: "#78350F",
                          }}
                        >
                          Page {h.pageNum}
                        </span>
                      </div>
                      <p
                        className="text-xs italic leading-relaxed"
                        style={{
                          color: "#0F172A",
                          fontFamily: "'Source Serif 4', Georgia, serif",
                        }}
                      >
                        "{h.text}"
                      </p>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Brief Footer */}
            <div
              className="border-t pt-4 text-center text-[10px] font-mono"
              style={{
                borderColor: "#E2E8F0",
                color: "#64748B",
              }}
            >
              SUITS Intelligence & Research Vault • Confidential Case Workspace
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
